nome = str(input('Qual o seu nome? '))
print('É um prazer te conhecer {}!'.format(nome))
print('É um prazer te conhecer {:20}!'.format(nome))
print('É um prazer te conhecer {:>20}!'.format(nome))
print('É um prazer te conhecer {:<20}!'.format(nome))
print('É um prazer te conhecer {:^20}!'.format(nome))
print('É um prazer te conhecer {:=^20}!'.format(nome))
print('É um prazer te conhecer {:-^20}!'.format(nome))
